#
# This workflow will build/test/lint the .NET SDK.
#

name: DOTNET Build/Test/Lint

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ['**']
    paths: ['.github/workflows/dotnet-*.yml', 'dotnet/**']

permissions: read-all

jobs:
  build-test-lint:
    name: Build/Test/Lint
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0', '7.0']
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: dotnet/packages/Microsoft.TeamsAI/
    env:
      SOLUTION_DIR: dotnet/packages/Microsoft.TeamsAI/
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore Microsoft.Teams.AI.sln
      - name: Build
        run: dotnet build Microsoft.Teams.AI.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test Microsoft.TeamsAI.Tests/Microsoft.Teams.AI.Tests.csproj --no-restore --verbosity normal --logger trx --results-directory ./TestResults --collect:"XPlat Code Coverage" --configuration Release
      - name: Coverage
        uses: danielpalme/ReportGenerator-GitHub-Action@c38c522d4b391c1b0da979cbb2e902c0a252a7dc # 5.4.3
        with:
          reports: ${{ env.SOLUTION_DIR }}TestResults/*/coverage.cobertura.xml
          targetdir: ${{ env.SOLUTION_DIR }}TestResults/coverage
          reporttypes: 'HtmlInline;lcov'
          toolpath: ${{ env.SOLUTION_DIR }}report-generator-tool
      - name: Upload Tests
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: testresults-dotnet-${{ matrix.dotnet-version }}
          path: ${{ env.SOLUTION_DIR }}TestResults
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit
