#
# This workflow will publish .NET SDK.
#

name: DOTNET Publish

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['dotnet/**']

permissions: read-all

jobs:
  build-test-lint:
    name: Build/Test/Lint
    uses: ./.github/workflows/dotnet-build-test-lint.yml
    permissions: read-all
  publish:
    name: Publish
    needs: build-test-lint
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0', '7.0']
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: dotnet/packages/Microsoft.TeamsAI/
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Pack
        run: dotnet pack --output . --configuration Release Microsoft.TeamsAI/Microsoft.Teams.AI.csproj
      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/microsoft/index.json --skip-duplicate --no-symbols
      - name: Upload
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: nupkg-dotnet-${{ matrix.dotnet-version }}
          path: dotnet/packages/Microsoft.TeamsAI/*.nupkg
